apiVersion: apps/v1
kind: Deployment
metadata:
  name: timline-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: my-nodejs-app-container
        image: mbhmma/test-repo:simpapp
        ports:
        - containerPort: 3000