#service resource type nodeport
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
spec:
  type: NodePort
  selector:
    app: my-nodejs-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30100